# Generated by Django 6.0.3 on 2026-04-04 13:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user_info',
            name='email',
        ),
    ]
