# Generated by Django 6.0.3 on 2026-04-06 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0002_remove_user_info_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_info',
            name='phone',
            field=models.CharField(max_length=15),
        ),
    ]
