# Generated by Django 6.0.3 on 2026-04-06 11:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payapp', '0002_transactions'),
    ]

    operations = [
        migrations.RenameField(
            model_name='balance',
            old_name='name',
            new_name='user',
        ),
    ]
