# Generated by Django 6.0.3 on 2026-04-07 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payapp', '0003_rename_name_balance_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='transactions',
            name='event_type',
            field=models.CharField(choices=[('_r', 'request'), ('ar', 'accepted request'), ('rr', 'rejected_request'), ('sp', 'sent_payment'), ('rp', 'received_payment')], default='', max_length=2),
        ),
    ]
