# Generated by Django 6.0.3 on 2026-04-07 12:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payapp', '0004_transactions_event_type'),
    ]

    operations = [
        migrations.RenameField(
            model_name='notifications',
            old_name='user_requesting',
            new_name='user_receiving_notif',
        ),
        migrations.RenameField(
            model_name='notifications',
            old_name='name',
            new_name='user_sending_notif',
        ),
        migrations.RenameField(
            model_name='transactions',
            old_name='other',
            new_name='user_receiving_transaction',
        ),
        migrations.RenameField(
            model_name='transactions',
            old_name='name',
            new_name='user_sending_transaction',
        ),
    ]
